import type { Metadata } from "next";
import { Inter, Roboto_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import ConditionalHeader from "../components/common/ConditionalHeader";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

/* Load primary body and mono fonts. Pretendard is referenced via CSS stack. */
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-theme="light">
      <head>
        <link rel="stylesheet" as="style" crossOrigin="" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
      </head>
      <body className={`${inter.variable} ${robotoMono.variable} ${montserrat.variable} antialiased`}>
        <ReactQueryProvider>
          <ConditionalHeader />
          {/* No fixed padding; header component inserts spacer only when visible */}
          <div>{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
